<a href="https://colab.research.google.com/github/moustafa-mk/Biometric-Authentication-using-Brain-Signals/blob/main/LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import scipy.io
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers import LSTM
from keras.utils import to_categorical

In [ ]:
np.random.seed(2)

In [ ]:
arrc = scipy.io.loadmat("/content/drive/MyDrive/BED dataset/Features/Verification/ARRC.mat")

In [ ]:
data = np.array(arrc['DATA'][0])

In [ ]:
data.shape

(14876,)

In [ ]:
data = np.expand_dims(data, -1)

In [ ]:
data[0][0][0][0][0][2].shape

(17, 14)

In [ ]:
data[0][0][3]

array([[1]], dtype=uint8)

In [ ]:
data[1000][0][1][0][0]

23

In [ ]:
print(data.shape)
X = []
y = []
cnt = 0
for row in data:
    # print(row[0][0][0][0][2].shape)    #last index is stimuli
    # print(len(row[0][0][0][0][2][11]))
    # break
    # temp = row[0][0][0][0][2][10:11]
    # task_row = []
    # for task_trial in temp:
    #     task_trial_array = np.array(task_trial)
    #     # print(task_trial_array)
    #     task_row.append(task_trial_array)
    # # print(np.array(task_row).shape)
    # # break
    # task_row = np.array(task_row)
    # task_row = np.array(row[0][0][0][0][:10])
    task_row = np.array(row[0][0][0][0][2])
    # print(task_row.shape)
    if task_row.shape[0] != 17:
        continue
    task_row.reshape(17, 14)
    X.append(task_row)
    if row[0][1][0][0] == 9:  #subject number
        cnt += 1
        y.append(1)
    else:
        y.append(0)

X = np.array(X)
y = np.array(y)
# print(cnt)

(14876, 1)


In [ ]:
len(X)

14428

In [ ]:
len(y)

14428

In [ ]:
y[0:100]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y)
X_train = np.array(X_train)
y_train = to_categorical(np.array(y_train))
X_test = np.array(X_test)
y_test = to_categorical(np.array(y_test))

In [ ]:
X_train[0].shape

(17, 14)

In [ ]:
X_train.shape

(10821, 17, 14)

In [ ]:
y_train.shape

(10821, 2)

In [ ]:
y_train[0:100]

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.

In [ ]:
n_timesteps, n_features, n_outputs = X_train[0].shape[0], X_train[0].shape[1], y_train.shape[1]
model = Sequential()
model.add(LSTM(100, input_shape=X_train[0].shape))
model.add(Dropout(0.5))
model.add(Dense(100, activation='relu'))
model.add(Dense(n_outputs, activation='softmax'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
verbose, epochs, batch_size = 0, 15, 64
model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, verbose=verbose)

In [ ]:
_, accuracy = model.evaluate(X_test, y_test, batch_size=batch_size, verbose=0)

In [ ]:
accuracy

0.9603548645973206

In [ ]:
def get_data(subject_no, stimuli_no=2):
    X = []
    y = []
    cnt = 0
    for row in data:
        task_row = np.array(row[0][0][0][0][stimuli_no]) #last index is stimuli
        # print(task_row.shape)
        if task_row.shape[0] != 17:
            continue
        task_row.reshape(17, 14)
        X.append(task_row)
        if row[0][1][0][0] == subject_no:  #subject number
            cnt += 1
            y.append(1)
        else:
            y.append(0)

    X = np.array(X)
    y = np.array(y)
    return X, y

In [ ]:
def build_model(X_train, y_train):
    n_timesteps, n_features, n_outputs = X_train[0].shape[0], X_train[0].shape[1], y_train.shape[1]
    model = Sequential()
    model.add(LSTM(100, input_shape=X_train[0].shape))
    model.add(Dropout(0.5))
    model.add(Dense(100, activation='relu'))
    model.add(Dense(n_outputs, activation='softmax'))
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model
    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

In [ ]:
min_accuracy, avg_accuracy, max_accuracy = 1.0, 0.0, 0.0
for sub in range(1, 22):
    X, y = get_data(sub)
    X_train, X_test, y_train, y_test = train_test_split(X, y)
    X_train = np.array(X_train)
    y_train = to_categorical(np.array(y_train))
    X_test = np.array(X_test)
    y_test = to_categorical(np.array(y_test))

    model = build_model(X_train, y_train)
    
    verbose, epochs, batch_size = 0, 15, 64
    model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, verbose=verbose)
    
    _, accuracy = model.evaluate(X_test, y_test, batch_size=batch_size, verbose=0)
    min_accuracy = min(min_accuracy, accuracy)
    max_accuracy = max(max_accuracy, accuracy)
    avg_accuracy += accuracy/21

print("min_accuracy: {0}".format(min_accuracy))
print("max_accuracy: {0}".format(max_accuracy))
print("avg_accuracy: {0}".format(avg_accuracy))

min_accuracy: 0.9459384679794312
max_accuracy: 1.0
avg_accuracy: 0.9719328795160567
